In [ ]:
import numpy as np
import pandas as pd

df=pd.read_csv("C:\\Users\\Waris Hayyat\\Desktop\\Pandas-Numpy Work\\carprices.csv")
df

In [18]:
dummies=pd.get_dummies(df)

dummies=dummies[['Car Model_Audi A5','Car Model_BMW X5','Car Model_Mercedez Benz C class']]

In [19]:
dummies

    Car Model_Audi A5  Car Model_BMW X5  Car Model_Mercedez Benz C class
0               False              True                            False
1               False              True                            False
2               False              True                            False
3               False              True                            False
4               False              True                            False
5                True             False                            False
6                True             False                            False
7                True             False                            False
8                True             False                            False
9               False             False                             True
10              False             False                             True
11              False             False                             True
12              False             False                             True

In [23]:
dummies_df=pd.concat([df,dummies],axis="columns")
dummies_df

,Car Model,Mileage,Sell Price($),Age(yrs),Car Model_Audi A5,Car Model_BMW X5,Car Model_Mercedez Benz C class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True
10,Mercedez Benz C class,83000,20000,7,False,False,True
11,Mercedez Benz C class,79000,21000,7,False,False,True
12,Mercedez Benz C class,59000,33000,5,False,False,True

In [24]:
dummies_df.drop(columns=["Car Model"],inplace=True)

In [26]:
dummies_df.drop(columns=["Car Model_Mercedez Benz C class"],inplace=True)

In [28]:
dummies_df

    Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000          18000         6              False              True
1     35000          34000         3              False              True
2     57000          26100         5              False              True
3     22500          40000         2              False              True
4     46000          31500         4              False              True
5     59000          29400         5               True             False
6     52000          32000         5               True             False
7     72000          19300         6               True             False
8     91000          12000         8               True             False
9     67000          22000         6              False             False
10    83000          20000         7              False             False
11    79000          21000         7              False             False
12    59000          33000         5              False             False

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
le=OneHotEncoder()

In [50]:
dummies_df

    Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5
0     69000          18000         6              False              True
1     35000          34000         3              False              True
2     57000          26100         5              False              True
3     22500          40000         2              False              True
4     46000          31500         4              False              True
5     59000          29400         5               True             False
6     52000          32000         5               True             False
7     72000          19300         6               True             False
8     91000          12000         8               True             False
9     67000          22000         6              False             False
10    83000          20000         7              False             False
11    79000          21000         7              False             False
12    59000          33000         5              False             False

In [52]:
dummies_df.keys()

Index(['Mileage', 'Sell Price($)', 'Age(yrs)', 'Car Model_Audi A5',
       'Car Model_BMW X5'],
      dtype='object')

In [63]:
X=dummies_df[['Mileage', 'Age(yrs)', 'Car Model_Audi A5',
       'Car Model_BMW X5']]

In [66]:
Y=dummies_df['Sell Price($)']

<class 'pandas.core.series.Series'>
RangeIndex: 13 entries, 0 to 12
Series name: Sell Price($)
Non-Null Count  Dtype
--------------  -----
13 non-null     int64
dtypes: int64(1)
memory usage: 236.0 bytes

In [70]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [73]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

Model=LinearRegression()

In [75]:
Model=LinearRegression()

In [78]:
Model.fit(X_train,Y_train)

LinearRegression()

In [85]:
from sklearn.preprocessing import LabelEncoder

In [83]:
Model.predict([[8000,6,0,1]])

C:\Users\Waris Hayyat\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([63310.36766385])

In [89]:
df=pd.read_csv("C:\\Users\\Waris Hayyat\\Desktop\\Pandas-Numpy Work\\carprices.csv")
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [104]:
le=LabelEncoder()

In [105]:
dfle=df

In [106]:
dfle

                Car_Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [107]:
df.rename(columns = {'Car Model':'Car_Model'}, inplace = True)

                Car_Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [110]:
dfle.Car_Model=le.fit_transform(dfle.Car_Model)
dfle

    Car_Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [111]:
df

    Car_Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [112]:
x=df[['Car_Model',"Mileage","Age(yrs)"]]

In [113]:
y=df[['Sell Price($)']]

In [114]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [119]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [120]:
model=LinearRegression()

In [121]:
model.fit(x_train,y_train)

LinearRegression()

In [122]:
acuracy=model.score(x_test,y_test)

In [123]:
print(acuracy)

-7.248301159907001

In [ ]:
model.predict([[]])